site_name: Taufiq Documentation
site_url: https://taufiqpsumarna.my.id

# Website Theme
theme:
  favicon: images/favicon/infinity-solid.png
  name: material
  icon:
    logo: fontawesome/solid/infinity
  font:
    text: Noto Sans
    code: Inconsolata
  features:
    - toc.follow
    - navigation.top
    - navigation.tabs
    - navigation.prune
    - navigation.indexes
    - content.code.annotate
    - search.share

# Pallete
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

#Plugins

plugins:
  - privacy
  - blog:
      blog_dir: blog
      post_readtime: true
      draft: true
      authors: true
      authors_file: "{blog}/.authors.yml"
  - search:
  - social:
      enabled: !ENV [CI, false]
  - tags:
      tags_file: tags.md
  - group:
      plugins:
        - optimize
        - minify

# Extension

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true


# Navigation Bar
nav:
  - Home: index.md
  - About Me: aboutme.md
  - Portfolio: portfolio.md
  - Blog:
    - blog/index.md
  - Contact: contact.md

# Javascript:
extra_javascript:
  - scripts/copyright.js

# Footer
extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/taufiqpsumarna
    - icon: fontawesome/brands/github
      link: https://github.com/taufiqpsumarna
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/taufiqpsumarna
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/taufiq14s
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/users/15878247/taufiq
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/taufiqpsumarna
    - icon: fontawesome/brands/medium
      link: https://medium.com/@taufiqpsumarna
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
copyright: >
  Copyright &copy; <span id="copyright-year"></span> <a href="/"> taufiqpsumarna.my.id – <a href="#__consent">Change cookie settings</a>