---
# Project information
site_name: taufiqpsumarna.my.id
site_url: https://taufiqpsumarna.my.id
site_author: M Taufiq Permana Sumarna
site_description: >-
  My Personal Portfoliom, Blog and Documentation
# Website Theme
theme:
  language: en
  favicon: assets/images/favicon/favicon.png
  name: material
  icon:
    logo: fontawesome/solid/infinity
  font: 
    text: Noto Sans
    code: Inconsolata
  features:
    - announce.dismiss
    - content.code.copy
    - content.tooltips
    - toc.follow
    - navigation.top
    - navigation.tabs
    - navigation.prune
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
    - search.share
    - search.highlight
    - search.suggest
# Pallete
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
#Plugins
plugins:
  - blog:
      blog_dir: blog
      post_readtime: true
      authors: true
      authors_file: "{blog}/.authors.yml"
      draft: false
      draft_on_serve: true
      draft_if_future_date: true
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - social:
      enabled: !ENV [CI, false]
  - tags:
      tags_file: tags.md
  - git-revision-date-localized:
      enable_creation_date: true
  - group:
      plugins:
        - optimize
        - minify
# Extension
markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
# Navigation Bar
nav:
  - Home: index.md
  - About Me: aboutme.md
  - Portfolio: portfolio.md
  - Blog:
    - blog/index.md
  - Contact: contact.md
  - Docs:
     - Handbook:
        - DevOps:
            - handbook/devops/intro.md
#  - gitGraph: gitgraph.md
# Extras
extra_javascript:
  - scripts/copyright.js
  
# Footer
extra:
  generator: false
  alternate:
    - name: Indonesia
      link: /id/ 
      lang: id
  social:
    - icon: material/gmail
      link: mailto:taufiqpsumarna@gmail.com
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/taufiqpsumarna
    - icon: fontawesome/brands/github
      link: https://github.com/taufiqpsumarna
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/taufiqpsumarna
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/taufiq14s
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/users/15878247/taufiq
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/taufiqpsumarna
    - icon: fontawesome/brands/medium
      link: https://medium.com/@taufiqpsumarna
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
copyright: >
  Copyright &copy; 2024</span> | <a href="/"> Privacy and Policy </a> | <a href="/terms-and-condition.md"> Terms and Condition </a> | <a href="/"> taufiqpsumarna.my.id – <a href="#__consent">Change cookie settings</a>