site_name: Taufiq Documentation
site_url: https://docs.taufiqpsumarna.my.id
theme:
  name: material
  features:
    - navigation.instant

  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - privacy
  - blog:
      blog_dir: blog
  - search
  - social:
      enabled: !ENV [CI, false]
  - tags
  - group:
      enabled: !ENV CI
    
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
copyright: >
  Copyright &copy; 2024-2024 M Taufiq Permana Sumarna –
  <a href="#__consent">Change cookie settings</a>