authors:
  taufiqpsumarna:
    name: Taufiq
    description: Author
    avatar: https://gravatar.com/avatar/7ecda104b27909e307bb8ad31bc92dcf377e661b4be058072e9d1adb92375bb2?s=200
    slug: admin
    url: https://taufiqpsumarna.my.id