name: Secret Scanning
on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@v3.76.1
      with:
        extra_args: --only-verified